print('Please enter the following:')
print()
name = input('name of a person: ')
emotion = input('emotion: ')
adjective = input('adjective: ')
exclamation = input('exclamation: ')
verb = input('verb: ')
verb_two = input('verb: ')
adjective_two = input('adjective: ')
print()
print('Your story is: ')
print()
print(f'Once upon a time, {name} received a special invitation to join an epic space expedition. With a heart full of {emotion}, they boarded the {adjective} spaceship, ready for the journey of a lifetime.')
print(f'Their first expedition was going to Mars. Whenever they got there they said {exclamation}! It was such a different and beautiful planet. They got off the spaceship and {verb} so much! They were so excited to be there where they encountered a colony of creatures with the ability to {verb_two}.')
print(f'As they returned home, {name} could not help but reflect on the incredible adventure they had experienced. It was a journey filled with {adjective_two} moments and newfound friendships, forever etched in their memory.')